name: test 2
  
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: setup 
      uses: actions/checkout@v4

    - name: sleep
      run: sleep 5
    - name: Download file with wget
      run: |
          wget -O get-cookies.txt-locally_v0.7.2_chrome.zip \
          "https://github.com/kairi003/Get-cookies.txt-LOCALLY/releases/download/v0.7.2/get-cookies.txt-locally_v0.7.2_chrome.zip"


    - name: Commit and push
      run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add get-cookies.txt-locally_v0.7.2_chrome.zip
          git commit -m "Done" || echo "No changes"
          git push  
          
      

